import os
from datetime import datetime


def generate_html(ai_response, pdf_name):

    os.makedirs("reports", exist_ok=True)

    results = ai_response["results"]

    compliance = ai_response["overall_compliance"]

    generated_time = datetime.now().strftime(
        "%d %B %Y %I:%M %p"
    )

    total = len(results)

    passed = len(
        [x for x in results if x["status"] == "PASS"]
    )

    failed = len(
        [x for x in results if x["status"] == "FAIL"]
    )

    partial = len(
        [x for x in results if x["status"] == "PARTIAL"]
    )
    summary = f"""
    The uploaded documentation was compared with the extracted website pages.
    Out of {total} requirements, {passed} passed,
    {failed} failed and {partial} were partially implemented.
    The report highlights missing or partially implemented
    features to help identify documentation and UI mismatches.
    """
    html = f"""
<html>

<head>

<title>Documentation Compliance Report</title>

<style>

body{{
font-family:Arial;
background:#f4f4f4;
margin:20px;
}}

h1{{
text-align:center;
color:#1976d2;
}}

.summary{{
background:white;
padding:20px;
border-radius:10px;
margin-bottom:20px;
}}

.info{{
background:white;
padding:15px;
border-radius:10px;
margin-bottom:20px;
}}

table{{
width:100%;
border-collapse:collapse;
background:white;
table-layout:fixed;
}}

th,td{{
border:1px solid #ccc;
padding:10px;
text-align:left;
vertical-align:top;
}}

th{{
background:#1976d2;
color:white;
}}

.PASS{{
color:green;
font-weight:bold;
}}

.FAIL{{
color:red;
font-weight:bold;
}}

.PARTIAL{{
color:orange;
font-weight:bold;
}}

img{{
border:1px solid #aaa;
border-radius:6px;
max-width:100%;
height:auto;
}}

th:nth-child(1){{
width:23%;
}}

th:nth-child(2){{
width:8%;
}}

th:nth-child(3){{
width:10%;
}}

th:nth-child(4){{
width:29%;
}}

th:nth-child(5){{
width:30%;
}}

</style>

</head>

<body>

<h1>Documentation Compliance Report</h1>

<div class="info">

<p><b>Generated On :</b> {generated_time}</p>

<p><b>Uploaded PDF :</b> {pdf_name}</p>

</div>

<div class="summary">

<h2>Overall Compliance : {compliance}%</h2>

<h3 style="color:green;">PASS : {passed}</h3>

<h3 style="color:red;">FAIL : {failed}</h3>

<h3 style="color:orange;">PARTIAL : {partial}</h3>

<h3>Total Requirements : {total}</h3>

</div>

<table>

<tr>

<th>Requirement</th>

<th>Status</th>

<th>Page</th>

<th>Reason</th>

<th>Screenshot</th>

</tr>
"""

    for item in results:

        page = item["page"].lower().replace(" ", "_")

        screenshot_file = f"reports/screenshots/{page}.png"

        if (
            item["status"] in ["FAIL", "PARTIAL"]
            and os.path.exists(screenshot_file)
        ):

            screenshot_html = f"""
            <img src="/screenshots/{page}.png" width="350">
            """

        else:

            screenshot_html = """
            <span style="color:gray;">
            No Screenshot
            </span>
            """

        if item["status"] == "PASS":

            row_color = "#e8f5e9"

        elif item["status"] == "PARTIAL":

            row_color = "#fff8e1"

        else:

            row_color = "#ffebee"

        html += f"""

<tr style="background:{row_color};">

<td>{item['requirement']}</td>

<td class="{item['status']}">
{item['status']}
</td>

<td>{item['page']}</td>

<td>{item['reason']}</td>

<td>{screenshot_html}</td>

</tr>

"""

    html += """

</table>

<br>

<hr>

<p style="text-align:center;color:gray;">

Generated by Documentation Compliance Agent

</p>

</body>

</html>

"""

    with open(
        "reports/compliance_report.html",
        "w",
        encoding="utf-8"
    ) as file:

        file.write(html)

    print("Professional HTML Report Generated Successfully")